# AutoQuant 설정 파일

# 데이터 수집 설정
data_collection:
  # 기본 시장
  default_market: KOSPI

  # 수집할 상위 종목 수
  top_n_stocks: 100

  # 데이터 수집 기간 (일)
  history_days: 365

  # 재시도 설정
  retry_count: 3
  retry_delay: 1

  # 수집 스케줄 (cron 형식)
  schedule:
    # 평일 오후 6시
    daily: "0 18 * * 1-5"

# 데이터베이스 설정
database:
  type: sqlite  # sqlite, postgresql, mysql
  path: data/autoquant.db

  # PostgreSQL 설정 (선택사항)
  postgresql:
    host: localhost
    port: 5432
    database: autoquant
    username: user
    password: password

# 분석 및 예측 설정
analysis:
  # 예측 기간 (일)
  prediction_days: 7

  # 사용할 모델
  models:
    - LSTM
    - XGBoost
    - RandomForest

  # 기술적 지표
  technical_indicators:
    - SMA_20    # 20일 이동평균
    - SMA_60    # 60일 이동평균
    - EMA_12    # 12일 지수이동평균
    - RSI_14    # 14일 RSI
    - MACD      # MACD
    - BBands    # 볼린저 밴드
    - Volume    # 거래량

# 매매 전략 설정
trading_strategy:
  # 최대 보유 종목 수
  max_holdings: 10

  # 종목당 최대 투자 비율
  max_position_size: 0.15  # 15%

  # 손절매 비율
  stop_loss: -0.07  # -7%

  # 익절 비율
  take_profit: 0.15  # +15%

  # 최소 거래 금액
  min_trade_amount: 100000  # 10만원

# 포트폴리오 관리 설정
portfolio:
  # 초기 자본금
  initial_capital: 10000000  # 1천만원

  # 현금 보유 비율 (최소)
  min_cash_ratio: 0.1  # 10%

  # 리밸런싱 주기 (일)
  rebalancing_period: 7

# 로깅 설정
logging:
  level: INFO
  format: "{time:YYYY-MM-DD HH:mm:ss} | {level} | {message}"
  rotation: "1 day"
  retention: "30 days"

# 알림 설정
notification:
  enabled: false
  email:
    enabled: false
    smtp_server: smtp.gmail.com
    smtp_port: 587
    sender: your_email@gmail.com
    password: your_password
    recipients:
      - recipient@example.com

  slack:
    enabled: false
    webhook_url: https://hooks.slack.com/services/YOUR/WEBHOOK/URL
